version: '3.8'

services:
  postgres:
    image: postgres:15.7
    container_name: postgres-suscore
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: suscore
    networks:
      - rede-sus
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadminsuscore
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - rede-sus

volumes:
  postgres_data:

networks:
  rede-sus:
    driver: bridge